---
format: 
  gfm:
    toc: true
    toc-depth: 4
title: "typst-template.typ"
author: "Beth Jump"
date: "2025-04-11"
embed-resources: true
execute: 
  warning: false
  error: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

The `typst-template.typ` is where most of the formatting is done for your Quarto document. Some of the syntax is different here than it is in the Typst examples and tutorials.

Broadly speaking the `typst-template.typ` has two parts:

1. document defaults (`# let doc()`): here you set document defaults and reference parameters from the Quarto template YAML.  
2. page settings (the `= {...}` after `# let doc`): here you can specify page defaults, how elements appear and the general flow of elements in the document.

General outline of a template: 

```
# let doc(
    title: none,
    paper: "us-letter",
    ...
) = {
    set page(paper: paper,
             header: context{...})
             
    place(center + top,
          ...)
          
    linebreak()
    set text(...)
}

```

## Document defaults

At the top of your `typst-template.typ`, you use the `# let` function to specify document defaults. Parameters that are set to `: none` will be pulled from the YAML of your Quarto template. Parameters with a value can be referenced later on in the template. 

If you want to add a custom value to your document, like `timeframe`, you need to also add it to the Quarto YAML and the `typst-show.typ`. 

Here's an example of how this part of a `typst-template.typ` might look:

```
#let doc(
  title: none,
  author: none,
  timeframe: none,
  program: none,
  cols: 1,
  margin: (x: 0.5in,
           top: 1.15in,
           bottom: 1in),
  paper: "us-letter",
  font: "Arial",
  fontsize: 11pt,
  title_font: "Trade Gothic Next Rounded",
  doc,
) 
```

## Page settings

All of your custom configuration is done after the `# let doc`:

```
# let doc( ) = {
    ...
    all custom configurations
    ...
}

```

### set page()

The `set page()` function allows you to specify page defaults for document. Anything you set within `set page()` doesn't respect the page margins. It is where you set the background of each page. Text and inline elements are set after `set page()` and will respect margins and the flow of text and document elements. 

You can use the `background:` to set an element anywhere on the page while `header:` and `footer:` are meant for elements at the top or bottom.  

#### header

`set page(header: ...)` is where you determine what appears in the header of each page. You can place objects and specify positions with `#place`. You can also use if else statements to have different elements appear on different pages.

In this example, we have a logo in the top right corner of the first page and have the title in size 16 font in the top right corner of subsequent pages. 

```
set page(paper: paper,
         header: context {
         
         // page 1 of the report
         if counter(page).get().first() == 1 [
         // logo
                #place(top + right,
                       dx: 0.3in,
                       dy: 0.3in,
                       image("images/logo.png",
                            width: 2.7in))
                            
               ] else [

                // title
                #place(top + right,
                       dx: 0.3in,
                       dy: 0.3in,
                       block(width: 5in,
                            height: 0.25in,
                            inset: 0.1in)[
                         #text(size: 16pt,
                               fill: rgb("000000"),
                               font: title_font,
                               top-edge: "cap-height",
                               bottom-edge: "descender",
                               align(right, title))])
               ]})
```

#### footer

Like with the header, you can set elements in the page footer dynamically or statically with `set page(header: ...)`.

```
set page(footer: context [

              // add department name ----
              #place(bottom + left,
                      dx: -0.4in,
                      dy: -0.05in,
                      block(width: 5in,
                            height: 0.5in,
                            inset: 0.1in)[
                                #text(weight: "bold",
                                      size: 14pt,
                                      fill: rgb("fefefe"),
                                      font: title_font,
                                      top-edge: "cap-height",
                                      bottom-edge: "descender")[#department]])

               // add page counter. First specify text and then specify placement ----
               #set text(size: 11pt,
                         fill: rgb("fefefe"),
                         font: title_font,
                         top-edge: "cap-height",
                         bottom-edge: "descender")
               #place(bottom + right,
                      dx: 0in,
                      dy: -0.18in,
                      counter(page).display("1 of 1", both: true))

                ])
```

#### background

You can use the same functions for `background:` as you can for `header:` and `footer:`. Here we place a teal colored bar horizontally across the first page of our document. The bar will start 0.95 inches from the top, will be 0.1 inches tall and will span the whole page: 

```
set page(background: context {
            if counter(page).get().first() > 1 [

                   #place(center + top,
                          dx: 0in,
                          dy: 0.95in,
                          rect(width: 8.5in,
                               height: 0.1in,
                               fill: rgb("38939b")))

           ]})
```

### placing objects

The `place()` function is an easy way to arrange objects on your page. A couple things to note:

* If you use `place()` within another function, like `set page()`, you should put a `#` in front of the function: `#place`.

```
set page(header: context[
                  #place(top + left,
                         ....)])
```

* If you place an object within `set page()` it will not respect the margins you specify. If you use `place()` after `set page()` it will place objects relative to the margins.

Documentation for `place()` is [here](https://typst.app/docs/reference/layout/place/).

### set vs show

Typst has some great documentation about [`set` vs `show`](https://typst.app/docs/reference/styling/) - check that out for details. 

At a high level: 

`set`: calls a function and allows you to use parameters within that function to customize an element. For example: `set text()` allows you to set text according to the parameters available to the `text()` function. 

`show`: allows you to customize an element with additional parameters not available to the function you're using. For example, text parameters aren't available in the `heading()` function, so you can use a `show` rule and `set text` with the `heading()` function to change the heading appearance:

```
show heading.where(level:1): set text(weight: "bold")
```

### block  vs box

This [book](https://sitandr.github.io/typst-examples-book/book/basics/must_know/box_block.html) goes over the differences but essentially `box()` lets you place things in line with text while `block()` creates a new paragraph. 


### text
#### headings

You can specify how headings appear in your final document using `show heading.where(level:n)`. where n is the heading level. The heading levels are off from the number of `#`'s by 1, so a heading denoted with `##` is a level 1 heading, `###` is a level 2 heading, etc. 

This is an example of how to format your level 1 (`## Heading Level 1`) headings:

```
show heading.where(level:1): set text(weight: "bold",
                                      size: 14pt,
                                      fill: rgb("000000"),
                                      font: font,
                                      top-edge: "ascender",
                                      bottom-edge: "descender")
```

#### body

Use `set par()` and `set text()` to specify how regular text appear in your report. See additional information for [`set par()`](https://typst.app/docs/reference/model/par/#parameters) and [`set text()`](https://typst.app/docs/reference/text/text/)

Here is an example of how to format your text:

```
set par(justify: false,
        leading: 0.5em)
set text(font: font,
         size: fontsize)
```
